name: CI
on:
  push:
    tags:
      - release/**
jobs:
  Publish:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install
      run: go mod tidy
    - name: Build
      run: GOOS=linux GOARCH=amd64 go build --ldflags "-extldflags -static -o ./release/server
    - uses: azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PWD }}
    - name: Publish
      run: |
        cd release
        IMAGE_TAG=${GITHUB_REF##*/}
        echo $IMAGE_TAG
        docker build --tag cjy632258/go-messenger:latest --tag cjy632258/go-messenger:$IMAGE_TAG .
        docker push cjy632258/go-messenger:latest
        docker push cjy632258/go-messenger:$IMAGE_TAG